context:
  name: hidimstat
  version: "0.4.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/h/hidimstat/hidimstat-${{ version }}.tar.gz
  sha256: 4d5ada7875c0328ce334634bde22674b42201d3db647cd47f864977901841411

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64,<100
    - setuptools-scm >=8,<50
    - pip
  run:
    - python >=${{ python_min }}
    - joblib >=1.4
    - pandas >=2.2
    - scikit-learn >=1.6
    - scipy >=1.13
    - tqdm >=4.66.3

tests:
  - python:
      imports:
        - hidimstat
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  homepage: https://pypi.org/project/HiDimStat/
  summary: High-dimensional statistical inference tools for Python
  repository: https://github.com/mind-inria/hidimstat
  documentation: https://github.com/hidimstat/hidimstat.github.io
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Yash990-bit
